### ISSUE TITLE
支持系统方法Hook吗

### ISSUE THREAD

**Issue by Nancy945** [FlyJingFish/AndroidAOP#1]
比如想hook 主工程、子工程、三方库中 所有的buttonClick事件 或者 textView的setText方法，用这个能做吗？ （并不需要真正hook系统方法，应该是通过调用的地方hook入口实现，类似aspectj）

**Comment by FlyJingFish** [comment]
[仔细阅读这个功能](https://github.com/FlyJingFish/AndroidAOP#%E4%BA%8Candroidaopmatchclassmethod-%E6%98%AF%E5%81%9A%E5%8C%B9%E9%85%8D%E6%9F%90%E7%B1%BB%E5%8F%8A%E5%85%B6%E5%AF%B9%E5%BA%94%E6%96%B9%E6%B3%95%E7%9A%84%E5%88%87%E9%9D%A2%E7%9A%84%EF%B8%8F%E6%B3%A8%E6%84%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84%E5%8C%B9%E9%85%8D%E7%B1%BB%E6%96%B9%E6%B3%95%E5%88%87%E9%9D%A2%E5%A6%82%E6%9E%9C%E6%98%AF-kotlin-%E4%BB%A3%E7%A0%81%E8%AF%B7%E7%94%A8-android-aop-ksp-%E9%82%A3%E4%B8%AA%E5%BA%93),只要代码是打进安装包里的，都可以切进去

**Comment by Nancy945** [comment]
谢谢 了解了
