### ISSUE TITLE
Hook内部类时没有生效

### ISSUE THREAD

**Issue by sunxu3074** [FlyJingFish/AndroidAOP#10]
### 描述一下大概怎么回事

在Hook内部类时没有生效

### 你的代码

```java
@AndroidAopReplaceClass("android.provider.Settings$Secure")
public class SettingsSecureHook {
//    invoke-static {v0, v1}, Landroid/provider/Settings$Secure;->getString(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;
    @AndroidAopReplaceMethod("java.lang.String getString(android.content.ContentResolver, java.lang.String)")
    public static String getString(ContentResolver resolver, String name) {
        Log.d("tag", "getString: " + name);
        return "";
    }

    @AndroidAopReplaceMethod("java.lang.String getString(android.content.ContentResolver, java.lang.String, int)")
    public static String getStringForUser(ContentResolver resolver, String name, int userHandle) {
        Log.d("tag", "getStringForUser: " + name);
        return "";
    }
}
```

```kotlin
// 生成的class
@AopClass
public final class `SettingsSystemHook$$AndroidAopClass` {
  @AopReplaceMethod(
    targetClassName = "android.provider.Settings${'$'}System",
    invokeClassName = "im.weshine.compliance.SettingsSystemHook",
  )
  public final fun aopConfigMethod() {
  }
}
```

```java
调用的代码
String androidId = Settings.Secure.getString(getApplicationContext().getContentResolver(), Settings.Secure.ANDROID_ID);
Log.d("tag", "androidid = "+androidId);
```

### 错误日志

过滤tag后只有调用的日志，没有被hook的日志。我在hook WifiInfo的getIpAddress和getMacAddress是成功的，只有hook内部类时没有成功。
```kotlin
@AndroidAopReplaceClass("android.net.wifi.WifiInfo")
object WifiInfoDelegate {
    @AndroidAopReplaceMethod("int getIpAddress()")
    @JvmStatic
    fun getIpAddress(info: WifiInfo) = 0

    @AndroidAopReplaceMethod("java.lang.String getMacAddress()")
    @JvmStatic
    fun getMacAddress(info: WifiInfo) = "02:00:00:00:00:00"
}
```

### 库的版本号:

1.4.7

**Comment by FlyJingFish** [comment]
1、内部类```android.provider.Settings$Secure```，应该这么表示```android.provider.Settings.Secure```，按我们平时导包的路径去写。不过这么写也不可以hook
2、重要的是你这种是不可以hook的，[点此查看原因](https://github.com/FlyJingFish/AndroidAOP?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。

**Comment by sunxu3074** [comment]
1. 我试过android.provider.Settings.Secure，同样也没有生效。
2. 我是觉得WIfiInfo这种能生效，android.provider.Settings.Secure同样也能生效吧。是不是内部类有特殊符号$导致的？

**Comment by FlyJingFish** [comment]
我说的第一点是教你怎么写内部类，不是说这么写就可以，hook类不在安装包里是不可以的，android.jar里的代码不可以hook

**Comment by sunxu3074** [comment]
我在安装包内建了一个内部类去hook，同样也没有成功。

```java
package com.demo

public class Test {
    public void a {}
    public void b {}
    public static final class Test1(){
        public String c() {
            return "c";
        }
    }
}
```

```kotlin
@AndroidAopReplaceClass("com.demo.Test.Test1")
object InnerHook {
    @AndroidAopReplaceMethod("java.lang.String c()")
    @JvmStatic
    fun c():String {
        return "cc"
    }
}
```

**Comment by FlyJingFish** [comment]
不好意思，我没仔细看你用的哪种注解，我以为是用的第二种……，下午我看下

**Comment by FlyJingFish** [comment]
[你再仔细看下这里](https://github.com/FlyJingFish/AndroidAOP?tab=readme-ov-file#%E4%B8%89androidaopreplaceclass-%E6%98%AF%E5%81%9A%E6%9B%BF%E6%8D%A2%E6%96%B9%E6%B3%95%E8%B0%83%E7%94%A8%E7%9A%84)，被替换调用的方法静态和非静态两种写法不一样。我在这里都有注释说明

**Comment by sunxu3074** [comment]
非常感谢，解决了。是我的问题，可能是我之前使用 <code>packagename.classname.innerclassname</code> 后没有clean，现在生效了。

**Comment by FlyJingFish** [comment]
> 非常感谢，解决了。是我的问题，可能是我之前使用 `packagename.classname.innerclassname` 后没有clean，现在生效了。
> 
> 另外，还是想再请教一下，假如这个c方法内有一个参数，如果c满足一定条件才hook，否则还是返回原值，该怎么写呢？
> 
> ```kotlin
> @AndroidAopReplaceClass("com.demo.Test.Test1")
> object InnerHook {
>     @AndroidAopReplaceMethod("java.lang.String c()")
>     @JvmStatic
>     fun c(content:String):String {
>        if(content.length > 3) {
>           return "ccc"
>        }
>        // 这里是再调用一次Test.Test1.c(content)吗？
>         return "cc"
>     }
> }
> ```

首先需要强调一点就是你的替换方法的函数签名必须按照[这里的说明](https://github.com/FlyJingFish/AndroidAOP?tab=readme-ov-file#%E4%B8%89androidaopreplaceclass-%E6%98%AF%E5%81%9A%E6%9B%BF%E6%8D%A2%E6%96%B9%E6%B3%95%E8%B0%83%E7%94%A8%E7%9A%84)来写
其次想要返回原方法的逻辑值分为两种情况
1、被替换方法是非静态方法的，你利用替换函数上定义的第一个参数，也就是原对象再调用被替换的方法即可，即```return 对象.方法名```

2、被替换方法是静态方法，你直接```return 类名.方法名```就行了

**Comment by sunxu3074** [comment]
通过<code>AndroidAopReplaceClass</code>这种形式，可不可以在内部拿到<code>ProceedJoinPoint</code>对象？这样我只需在一个单独的module中做所有需要hook的逻辑就可以，而不是必须在可以引用到<code>com.demo.Test.Test1</code>的module中。

```kotlin
@AndroidAopReplaceClass("com.demo.Test.Test1")
object InnerHook {
    @AndroidAopReplaceMethod("java.lang.String c()")
    @JvmStatic
    fun c(joinPoint: ProceedJoinPoint，content:String):String {
       if(content.length > 3) {
          return "ccc"
       }
       // return com.demo.Test.Test1.c(content)
       return joinPoint.proceed() as String
    }
}
```

**Comment by FlyJingFish** [comment]
> 通过`AndroidAopReplaceClass`这种形式，可不可以在内部拿到`ProceedJoinPoint`对象？这样我只需在一个单独的module中做所有需要hook的逻辑就可以，而不是必须在可以引用到`com.demo.Test.Test1`的module中。
> 
> ```kotlin
> @AndroidAopReplaceClass("com.demo.Test.Test1")
> object InnerHook {
>     @AndroidAopReplaceMethod("java.lang.String c(java.lang.String)")
>     @JvmStatic
>     fun c(joinPoint: ProceedJoinPoint，content:String):String {
>        if(content.length > 3) {
>           return "ccc"
>        }
>        // return com.demo.Test.Test1.c(content)
>        return joinPoint.proceed() as String
>     }
> }
> ```

1、想要用```ProceedJoinPoint```你只能用[@AndroidAopMatchClassMethod ](https://github.com/FlyJingFish/AndroidAOP/wiki/@AndroidAopMatchClassMethod)，但看你这种情况是想hook所有系统方法的调用，因此[@AndroidAopMatchClassMethod ](https://github.com/FlyJingFish/AndroidAOP/wiki/@AndroidAopMatchClassMethod)是不可以用的，因此```ProceedJoinPoint```也是无法使用的
2、咱们这个库写的所有自定义切面代码无论你写在哪个module，只要代码还在你最终的安装包里，是全局生效的（前提是如果你设置了[这里的 include exclude 规则，记得把它修改到足以覆盖你想要扫描到的所有module](https://github.com/FlyJingFish/AndroidAOP?tab=readme-ov-file#%E5%9B%9B%E5%9C%A8-app-%E7%9A%84buildgradle%E6%B7%BB%E5%8A%A0-androidaopconfig-%E9%85%8D%E7%BD%AE%E9%A1%B9%E6%AD%A4%E6%AD%A5%E4%B8%BA%E5%8F%AF%E9%80%89%E9%85%8D%E7%BD%AE%E9%A1%B9)）
3、相信上述两点已经为你解惑了，我写的另一个库[ModuleCommunication](https://github.com/FlyJingFish/ModuleCommunication)，可以做到模块间通信，你可以根据自身情况使用
