### ISSUE TITLE
AndroidAopPointCut 注解无效 (include 包名问题， 使用者问题)

### ISSUE THREAD

**Issue by liuxuwei** [FlyJingFish/AndroidAOP#11]
### 描述一下大概怎么回事
使用 AndroidAopPointCut 不生效,   自定义注解和注解处理类在 library 中， 在应用层的方法上标注 @ClickEvent()， 最终 ClickAop 类的 invoke 方法没有回调

### 你的代码

以下为定义的注解
----
@AndroidAopPointCut(ClickAop::class)
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
annotation class ClickEvent(val clickName: String, val clickInfo: String)

以下为注解处理类
----
class ClickAop: BasePointCut<ClickEventJava> {
   override fun invoke(joinPoint: ProceedJoinPoint, anno: ClickEvent): Any? {
       ClickTrack.trackClickEvent(anno.clickName)
        return joinPoint.proceed()
   }
}

### 错误日志
无
### 库的版本号:
1.4.7

**Comment by liuxuwei** [comment]
从头到尾配置的， AndroidAopMatchClassMethod 这个注解已经处理成功了

**Comment by FlyJingFish** [comment]
把这个注解加到其他类里边的某个方法上调用下

**Comment by FlyJingFish** [comment]
ClickAop  上边也没有写泛型呀

**Comment by FlyJingFish** [comment]
再就是你确定你加注的注解是你定义的那个吗，有没有用错同名不同包的

**Comment by liuxuwei** [comment]
写了泛型的，我刚刚在 cutInfo.json 中看了下， 只生成了 AndroidAopMatchClassMethod 注解定义的切面，  AndroidAopPointCut 这个切点相关的方法都没有搜到

**Comment by liuxuwei** [comment]
![image](https://github.com/FlyJingFish/AndroidAOP/assets/23065764/d94ded92-0b32-41e0-94d9-305d9dfd5e92)
![image](https://github.com/FlyJingFish/AndroidAOP/assets/23065764/74bb4b93-6a8b-49e0-88fa-029f6a4f6e4f)

**Comment by FlyJingFish** [comment]
> 写了泛型的，我刚刚在 cutInfo.json 中看了下， 只生成了 AndroidAopMatchClassMethod 注解定义的切面， AndroidAopPointCut 这个切点相关的方法都没有搜到

在这里没有看到说明没有找到加注注解的位置，你确定加了在方法上加了你定义的这个注解了，有没有设置include exclude

**Comment by liuxuwei** [comment]
include 设置的是我 app 的包名，  exclude 是按文档把 kotlin 相关的排除掉了，  是要把 kotlin.internal 这一项去掉吗
// 可排除 kotlin 相关，提高速度
    exclude 'kotlin.jvm', 'kotlin.internal','kotlinx.coroutines.internal', 'kotlinx.coroutines.android'

![image](https://github.com/FlyJingFish/AndroidAOP/assets/23065764/a6738b4d-5dc9-4cb6-b65f-f31b916fcc4f)
这个是代码中使用注解的地方

**Comment by FlyJingFish** [comment]
本库中内置的注解，你加了起作用吗

**Comment by FlyJingFish** [comment]
你加注解的这个类的包名在你设置的规则以内吗，把你代码贴全一点，跟挤牙膏似的
