### ISSUE TITLE
使用build.gradle.kts 引入 id 'android.aop'后报错

### ISSUE THREAD

**Issue by TSsimeon** [FlyJingFish/AndroidAOP#16]
### 描述一下大概怎么回事
例如使用什么功能时会这样

### 你的代码
把你的出现错误的代码关键部分贴出来

### 错误日志
把错误日志贴出来

### 库的版本号:
说明库版本号
kotlin版本1.9.0

**Comment by FlyJingFish** [comment]
什么报错，倒是贴出来呀😓

**Comment by TSsimeon** [comment]
![Uploading 微信图片_20240430153951.png…]()

**Comment by FlyJingFish** [comment]
你先在根目录加上如下设置，详细使用介绍看首页，待会我发一版

```
androidAop.reflectInvokeMethod = false
androidAop.debugMode = true
androidAop.debugMode.variantOnlyDebug = true
```

**Comment by FlyJingFish** [comment]
我这边没有报错，你之前设置上边三项配置了吗

**Comment by TSsimeon** [comment]
再gradle.properties中加入配置后,依然有问题

**Comment by FlyJingFish** [comment]
你用的是最新版吗

**Comment by TSsimeon** [comment]
插件版本1.6.6,gradle-8.4-bin,kotlin 1.9.0

**Comment by FlyJingFish** [comment]
这应该是较新的gradle版本缺少对应的方法了，我待会发一版

**Comment by TSsimeon** [comment]
麻烦了。

**Comment by FlyJingFish** [comment]
[1.6.8已修复](https://github.com/FlyJingFish/AndroidAOP/releases/tag/1.6.8)
