### ISSUE TITLE
AndroidAopPointCut 注解无效

### ISSUE THREAD

**Issue by Payaml** [FlyJingFish/AndroidAOP#18]
### 描述一下大概怎么回事
自定义注解和注解处理类在 library 中， 在应用层的方法上标注 @LoginInterceptor()， 最终 LoginAop 类的 invoke 方法没有调用

### 你的代码
项目根目录的 build.gradle
![QQ截图20240604175011](https://github.com/FlyJingFish/AndroidAOP/assets/25782462/06a0db85-4e59-4d06-bf13-f2f10ee52ed4)

app 的 build.gradle
![2](https://github.com/FlyJingFish/AndroidAOP/assets/25782462/e6fe16aa-ba20-405c-9dac-c0a6af72ab1e)

依赖库在 Library 中引入
![3](https://github.com/FlyJingFish/AndroidAOP/assets/25782462/63b53746-1ebf-4f86-afaa-c81068e22ac3)

Library 中的切入代码
![4](https://github.com/FlyJingFish/AndroidAOP/assets/25782462/fec07dfe-8fb1-4ad0-bca2-ce71d1e987a9)
![5](https://github.com/FlyJingFish/AndroidAOP/assets/25782462/1a2495fa-6b82-459e-b13c-57bf1f225463)

app 中使用
![6](https://github.com/FlyJingFish/AndroidAOP/assets/25782462/331f7e43-b1bc-444d-940d-6d3bfc8d6485)

### 错误日志
无

### 库的版本号:
Gradle 8.7
aop 1.8.2

**Comment by Payaml** [comment]
> #11 你参考下这里

参考了，之前是用 AspectJx，配置上基本差不多，我 include 的包名是正确的，文档的配置流程也对照着看了很多遍，但AndroidAopPointCut 依然不执行，cutInfoJson true Json 文件也不会生成，不知道是我哪里的配置没搞好，麻烦大佬帮忙看一下

**Comment by FlyJingFish** [comment]
你应用debugMode了吗

**Comment by FlyJingFish** [comment]
#### 我看到你很多地方的配置完全没有按照配置要求来

1、从第一个图就不太对，第一步决定了 debugMode 是否能生效（无论是否使用debugMode，都尽量按照要求，因为没有副作用，相反你突然想用debugMode了，这里又按要求配置，等出了问题你自己可能都不知道咋回事）

2、第二个图，我明确说了放在最好放在最后一行

3、第三个图，我只看到了2个貌似关于 AndroidAOP 的库，配置步骤里明确写了至少配置3个

4、还有你说 cutInfo.json 没有生成。你根本没打开 `cutInfoJson` 

#### 其他网友出现你这种问题的还有如下几个原因：

1、注解导错包了。

2、include exclude 填小了。

3、配置完没有clean项目。

**Comment by Payaml** [comment]
> #### 我看到你很多地方的配置完全没有按照配置要求来
> 1、从第一个图就不太对，第一步决定了 debugMode 是否能生效（无论是否使用debugMode，都尽量按照要求，因为没有副作用，相反你突然想用debugMode了，这里又没按要求配置，等出了问题你自己可能都不知道咋回事）

这里用 false ，在需要使用的 model 中引入插件，效果是一样的吧

> 
> _**2、第二个图，我明确说了最好放在最后一行,你的大概率是这步出问题了**_

放在最后一行的话，编译会出错，请参考 Gradle 8 的文档，id 引入只能放在 alias 的上面

> 
> 3、第三个图，我只看到了2个貌似关于 AndroidAOP 的库，配置步骤里明确写了至少配置3个

这是 Group 引入

> 
> 4、还有你说 cutInfo.json 没有生成。你根本没打开 `cutInfoJson`

打开了 cutInfoJson = true，因为没效果，所以又去掉了

> 
> #### 其他网友出现你这种问题的还有如下几个原因：
> 1、注解导错包了。
> 
> 2、include exclude 填小了。
> 
> 3、配置完没有clean项目。

**Comment by FlyJingFish** [comment]
我费心给你分析一遍，说的这几个原因有的是建议有的是原因，你还一一反驳一遍。我说的最可能的原因给你加粗斜体了，你都反驳一下。99%是第二个原因，真显着你了。还有既然提了issues就不要乱删。这也是后来者参考的地方
