### ISSUE TITLE
对于运行时动态织入代码的支持

### ISSUE THREAD

**Issue by eternallyjie** [FlyJingFish/AndroidAOP#20]
### 详细说明功能
请问是否考虑不仅仅是编译时静态织入代码，新增运行时动态织入代码功能呢？
有如下场景：比如在安全隐私管控上（如读取用户手机信息、imei、权限申请等），大多都会接入第三方库或者 sdk 之类的，这些库如果是正常静态代码调用相关 api，那目前的编译时织入代码没问题，但如果是通过 c 层反射调用或者通过下发插件之类的形式，那么就无法进行相关管控和检测。
所以希望增加运行时动态织入代码的能力支持。

**Comment by FlyJingFish** [comment]
你遇到的具体场景描述一下

**Comment by eternallyjie** [comment]
> 你遇到的具体场景描述一下

目前遇到的场景是对于 android.telephony.TelephonyManager.getImei 这个 api，我们有做编译时代码织入不调用到系统 api，直接返回空字符串，但是在安全检测的时候却发现还是有调用该系统 api 的情况存在，而且安全检测工具也拿不到具体的堆栈信息，所以猜测可能是通过 c 层反射调用或者是动态下发的插件调用的。
所以想通过在运行时进行代码织入进行相关 api 的拦截。

具体安全检测到的堆栈如下：

<img width="822" alt="image" src="https://github.com/user-attachments/assets/7e2451c6-df33-4399-804d-5004744e808e">

**Comment by eternallyjie** [comment]
> 你遇到的具体场景描述一下

目前遇到的场景是对于 android.telephony.TelephonyManager.getImei 这个 api，我们有做编译时代码织入不调用到系统 api，直接返回空字符串，但是在安全检测的时候却发现还是有调用该系统 api 的情况存在，而且安全检测工具也拿不到具体的堆栈信息，所以猜测可能是通过 c 层反射调用或者是动态下发的插件调用的。
所以想通过在运行时进行代码织入进行相关 api 的拦截。

具体安全检测到的堆栈如下：

![QQ_1721015374551](https://github.com/user-attachments/assets/eacfd8e3-160e-43ef-9924-c8776e04b58c)

**Comment by FlyJingFish** [comment]
> > 你遇到的具体场景描述一下
> 
> 目前遇到的场景是对于 android.telephony.TelephonyManager.getImei 这个 api，我们有做编译时代码织入不调用到系统 api，直接返回空字符串，但是在安全检测的时候却发现还是有调用该系统 api 的情况存在，而且安全检测工具也拿不到具体的堆栈信息，所以猜测可能是通过 c 层反射调用或者是动态下发的插件调用的。 所以想通过在运行时进行代码织入进行相关 api 的拦截。
> 
> 具体安全检测到的堆栈如下：
> 
> ![QQ_1721015374551](https://private-user-images.githubusercontent.com/30895476/348595094-eacfd8e3-160e-43ef-9924-c8776e04b58c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTU4NzQsIm5iZiI6MTcyMTAxNTU3NCwicGF0aCI6Ii8zMDg5NTQ3Ni8zNDg1OTUwOTQtZWFjZmQ4ZTMtMTYwZS00M2VmLTk5MjQtYzg3NzZlMDRiNThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDAzNTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZmEwZGFmYjBhZDI2NmFiMDBlZGQyMjM2OWZkYmI1MjhkMjk2MGQyODBjNWE5YTA2ZTI3ODAxNWRjNjA3MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IkV45wv4BUNnVnPjtaWRk1bgQGEzE4AKq44oWZkDJ5E)

你做的切面的代码发一下

**Comment by eternallyjie** [comment]
> > > 你遇到的具体场景描述一下
> > 
> > 
> > 目前遇到的场景是对于 android.telephony.TelephonyManager.getImei 这个 api，我们有做编译时代码织入不调用到系统 api，直接返回空字符串，但是在安全检测的时候却发现还是有调用该系统 api 的情况存在，而且安全检测工具也拿不到具体的堆栈信息，所以猜测可能是通过 c 层反射调用或者是动态下发的插件调用的。 所以想通过在运行时进行代码织入进行相关 api 的拦截。
> > 具体安全检测到的堆栈如下：
> > ![QQ_1721015374551](https://private-user-images.githubusercontent.com/30895476/348595094-eacfd8e3-160e-43ef-9924-c8776e04b58c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTU4NzQsIm5iZiI6MTcyMTAxNTU3NCwicGF0aCI6Ii8zMDg5NTQ3Ni8zNDg1OTUwOTQtZWFjZmQ4ZTMtMTYwZS00M2VmLTk5MjQtYzg3NzZlMDRiNThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDAzNTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZmEwZGFmYjBhZDI2NmFiMDBlZGQyMjM2OWZkYmI1MjhkMjk2MGQyODBjNWE5YTA2ZTI3ODAxNWRjNjA3MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IkV45wv4BUNnVnPjtaWRk1bgQGEzE4AKq44oWZkDJ5E)
> 
> 你做的切面的代码发一下

目前并非通过本库实现的切面，而是基于 https://github.com/Knight-ZXW/LancetX 这个库做的切面。

代码如下：

![QQ_1721016269790](https://github.com/user-attachments/assets/90290ae7-7983-4b69-8f97-367e17f3baab)

**Comment by FlyJingFish** [comment]
说明下：
1、我认为你说的 C 层反射调用，尤其是调用的还是 SDK 的代码，动态织入也和这个搭不上边吧。
2、另外本库是致力于将代码改造为AOP的工具库，因此我认为要想完全解决你这个问题这已经超出了本库定义的范畴了
