### ISSUE TITLE
How to target all classes in a specific package

### ISSUE THREAD

**Issue by haihack** [FlyJingFish/AndroidAOP#21]
I know that to log all methods of a class, I can use the following approach:

```
@AndroidAopMatchClassMethod(
    targetClassName = "com.example.main.MainActivity",
    methodName = ["*"],
    type = MatchType.SELF
)
class MatchActivityMethod : MatchClassMethod {
    override fun invoke(joinPoint: ProceedJoinPoint, methodName: String): Any? {
        Logger.e("${joinPoint.targetClass.simpleName}: $methodName()")

        return joinPoint.proceed()
    }
}
```

So how can I log all methods of all classes in a certain package?

I tried the following approach, but it doesn't work:

> `targetClassName = "com.example.main.*"`

**Comment by FlyJingFish** [comment]
Let me first say the conclusion. This library does not support this approach.
AndroidAOP currently only matches methods of a certain class, and does not match only a certain method regardless of which class it is. Because the author thinks that doing so is almost meaningless. Doing so often will result in many classes or methods that do not want to be added to the aspect being added, which is not conducive to everyone managing and controlling their own code (a bit out of control~)

**Comment by FlyJingFish** [comment]
Can you please tell me what is the actual scenario in which you do this? I will close this issue

**Comment by haihack** [comment]
Recently, I have been taking over the maintenance of a new project on my all. Since the project has no documents, I am not familiar with the project's structure, some workflows are encountering ARN errors due to loops.

Therefore, I want to print the logs of all the methods that will be called to understand the project's structure and identify the places where infinite loops are occurring.

I know that I can achieve this with the following code using AspectJ:

> @ Aspect
> public class ActivityLifecycleLogAspect {
>     private static final String TAG = ActivityLifecycleLogAspect.class.getSimpleName();
> 
>     // Define the package you want to target
>     private static final String TARGET_PACKAGE = 'com.your.package.name'; 
> 
>     @Pointcut('execution(* *(..)) && within(' + TARGET_PACKAGE + '..*)' +
>               '&& !within(ActivityLifecycleLogAspect)') 
>     public void logActivityLifecycle() {}
> 
>     @Before('logActivityLifecycle()')
>     public void log(final JoinPoint joinPoint) {
>         Log.v(TAG, 'log: ' + joinPoint.toLongString());
>     }
> }

I would be happy if you can make it with AndroidAOP

**Comment by FlyJingFish** [comment]
Many other friends have mentioned this feature before, but the reasons are not sufficient. I think the reason you mentioned is still valuable, so I will add this feature to the next version. It will be launched tonight at the earliest

**Comment by haihack** [comment]
Thank you!
Please make it possible to target not only the classes within a package but also all the classes in all its sub-packages.

**Comment by FlyJingFish** [comment]
> Thank you! Please make it possible to target not only the classes within a package but also all the classes in all its sub-packages.

That's for sure, the new version 2.0.2 with this feature has already been released.
