### ISSUE TITLE
实现了函数的注解，然后增加对函数参数的注解。如何在函数注解实现invoke处，判断具体参数是否有注解

### ISSUE THREAD

**Issue by zhouwenhao** [FlyJingFish/AndroidAOP#22]
实现了函数的注解，然后增加对函数参数的注解。如何在函数注解实现invoke处，判断具体参数是否有注解

这个是参数注解，无需实现，只需要注解到函数的参数即可
@Target(
    AnnotationTarget.VALUE_PARAMETER,
    AnnotationTarget.PROPERTY_GETTER,
    AnnotationTarget.PROPERTY_SETTER
)
@Retention(
    AnnotationRetention.RUNTIME
)
annotation class LogP()

这个是函数注解，需要实现
@AndroidAopPointCut(LogdCut::class)
@Target(
    AnnotationTarget.FUNCTION,
    AnnotationTarget.PROPERTY_GETTER,
    AnnotationTarget.PROPERTY_SETTER
)
@Retention(
    AnnotationRetention.RUNTIME
)
annotation class LOGD()

此处，始终无法判断具体某个参数是否被注解
override fun invoke(joinPoint: ProceedJoinPoint, anno: LOGD): Any? {
        val className = joinPoint.getTargetClass().simpleName
        val methodName = joinPoint.targetMethod.name
        val paramsList = joinPoint.args?.filter{
            println("xxxx $it")
            println("xxxx ${it?.javaClass is LogP}")
            it?.javaClass?.isAnnotationPresent(LogP::class.java) ?: false
        }?.map { it.toString() }
        AopLog.d("xxxxf->$className", "m->$methodName p->$paramsList")
        val result = joinPoint.proceed()
        return result
    }

**Comment by FlyJingFish** [comment]
最新版本 [2.0.3](https://github.com/FlyJingFish/AndroidAOP/releases/tag/2.0.3) 已具备此功能。
另外麻烦提问题前至少给点个免费的 Star！

**Comment by zhouwenhao** [comment]
请问一下，具体如何操作？或者仓库中的示例代码文件？

**Comment by FlyJingFish** [comment]
[在这](https://github.com/FlyJingFish/AndroidAOP/blob/master/test-lib/src/main/java/com/flyjingfish/test_lib/mycut/MyAnnoCut2.kt)

**Comment by FlyJingFish** [comment]
素质真够低的，点了star又取消了，自作聪明。
