### ISSUE TITLE
joinPoint.getTargetClass() 得到的是文件名，不是class名

### ISSUE THREAD

**Issue by zhouwenhao** [FlyJingFish/AndroidAOP#23]
joinPoint.getTargetClass() 得到的是文件名，不是class名，并且默认追加了"Kt"

override fun invoke(joinPoint: ProceedJoinPoint, anno: Logd): Any? {
        println("xxxx"+joinPoint.getTargetClass())

打印的是：xxxxclass com.example.kotlinstudy.MainActivityAAKt

MainActivityAAKt其实是文件名MainActivityAA.kt
实际的class是MainActivity

**Comment by FlyJingFish** [comment]
getTargetClass 是实际拿到的类的class对象。它的toString方法打印什么不是你我能决定的……ok？

**Comment by FlyJingFish** [comment]
还有kotlin的类生成的class有时候会自动加上kt，这是基本常识
