### ISSUE TITLE
Demo直接运行无效

### ISSUE THREAD

**Issue by aheven** [FlyJingFish/AndroidAOP#24]
### 描述一下大概怎么回事
Clone 后直接运行 app 项目，AOP 没有效果，找不到原因，看 ReplaceLog 日志初始化正常，请问是什么原因？

### 你的代码
无

### 错误日志
无

### 库的版本号:
最新代码

**Comment by FlyJingFish** [comment]
如果你看到了日志有 “ReplaceLog-”打印出来，代表已经成功了。
另外这里只解答关于此库出现的bug等问题。对于想研究学习的请自学即可
