### ISSUE TITLE
求助: 继承BasePointCut写的自定义注解无效

### ISSUE THREAD

**Issue by dengzhiguiios** [FlyJingFish/AndroidAOP#30]
### 描述一下大概怎么回事
拉取代码运行, 官方自带的@SingleClick是有效的, 但是自己复制改一下名字就无效了, 不知道为什么
没有报错信息, 复制模仿写的继承BasePointCut写的自定义注解无效

### 你的代码
自定义注解路径:com.flyjingfish.android_aop_core.annotations.ClickLimit
`@AndroidAopPointCut(ClickLimitCut::class)
@Retention(AnnotationRetention.RUNTIME)
@Target(
    AnnotationTarget.FUNCTION, AnnotationTarget.PROPERTY_GETTER, AnnotationTarget.PROPERTY_SETTER
)
annotation class ClickLimit(
    /**
     * 快速点击的间隔（ms），默认是1000ms
     */
    val limit: Long = DEFAULT_INTERVAL_MILLIS
) {
    companion object {
        const val DEFAULT_INTERVAL_MILLIS: Long = 1000
    }
}`

继承BasePointCut实现路径:com.flyjingfish.android_aop_core.cut.ClickLimitCut
`internal class ClickLimitCut : BasePointCut<ClickLimit> {
    override fun invoke(joinPoint: ProceedJoinPoint, anno: ClickLimit): Any? {
        println("test->ClickLimit:${System.currentTimeMillis()}")
        return null
    }
}`

测试代码:
`//    @SingleClick(5000)
    @ClickLimit(limit = 5000)
    fun onSingleClick() {
        Log.e("MainActivity", "onSingleClick:${System.currentTimeMillis()}")
        setLogcat("@SingleClick 5000毫秒内只能点击一次")
    }`

### 错误日志
没有输出期望的测试日志test->ClickLimit:时间戳

### 库的版本号:
官方demo, 没改任何配置信息

**Comment by FlyJingFish** [comment]
仔细看接入步骤
