### ISSUE TITLE
请问Gradle7.5.1 +AGP7.4.2可以用这个插件吗? 一定需要满足gradle7.6嘛?求解答

### ISSUE THREAD

**Issue by wangpei72** [FlyJingFish/AndroidAOP#32]
### 详细说明功能
详细说明功能是怎么回事

作者在这个库本来就是免费为大家服务，麻烦至少点个 Star ，没有Star的作者不会将你提到的新的需求排在前边

**Comment by FlyJingFish** [comment]
必须的，就差那么一点，直接升级不就行了，纠结什么
