### ISSUE TITLE
反射无法对产物包进行切面

### ISSUE THREAD

**Issue by Gavinme** [FlyJingFish/AndroidAOP#35]
### 描述一下大概怎么回事
例如使用什么功能时会这样
反射无法对产物包进行切面，看文档也是这么写的但是项目中用到组件化编译，大部分使用aar产物进行编译，开发过程中如果对jar包进行扫面会导致每次编译都会有dexBuilder耗时，能否将jar包进行缓存，这样可以减少dex过程的耗时，感谢

### 你的代码
把你的出现错误的代码关键部分贴出来

### 错误日志
把错误日志贴出来

### 库的版本号:
说明库版本号

### 电脑类别:
如：mac 还是 windows

**Comment by FlyJingFish** [comment]
哥们，提了两个问题了，点个star给个起码的尊重，如果觉得这个库连个star都不值得给，何必在这讨论呢

**Comment by FlyJingFish** [comment]
[常见问题 14 已经进行了解答](https://github.com/FlyJingFish/AndroidAOP/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#14%E7%BB%84%E4%BB%B6%E5%8C%96%E7%9A%84%E9%A1%B9%E7%9B%AE%E4%B8%8D%E5%90%8C-module-%E9%87%87%E7%94%A8%E7%9A%84%E6%96%B9%E6%A1%88%E6%98%AF-aar-%E8%BF%99%E6%A0%B7%E7%9A%84%E4%BA%A7%E7%89%A9%E8%BF%9B%E8%A1%8C%E7%BC%96%E8%AF%91%E5%A6%82%E4%BD%95%E5%8A%A0%E5%BF%AB%E6%89%93%E5%8C%85%E9%80%9F%E5%BA%A6%E5%91%A2)
