### ISSUE TITLE
二级目录的modules无法生成切面代码

### ISSUE THREAD

**Issue by Gavinme** [FlyJingFish/AndroidAOP#36]
### 描述一下大概怎么回事
例如使用什么功能时会这样

使用方式1接入在根目录下 apply plugin: 'android.aop' 二级目录的modules无法生成切面代码，一级的如app、common可以的
![image](https://github.com/user-attachments/assets/72725a4e-dc2f-4fde-9ce5-3961e770b3d1)

### 你的代码
把你的出现错误的代码关键部分贴出来

### 错误日志
把错误日志贴出来

### 库的版本号:
说明库版本号

### 电脑类别:
如：mac 还是 windows

**Comment by FlyJingFish** [comment]
你这是生产项目吗，还是你的demo

**Comment by Gavinme** [comment]
> 你这是生产项目吗，还是你的demo

生产的

**Comment by FlyJingFish** [comment]
最新版已修复
