### ISSUE TITLE
Translate Readme into English

### ISSUE THREAD

**Issue by RohitKushvaha01** [FlyJingFish/AndroidAOP#37]
Translating your repository will give much more exposure

**Comment by FlyJingFish** [comment]
![IMG_6212](https://github.com/user-attachments/assets/2ff51e9e-c315-43f3-8ecc-5acd50f328e0)
In fact, there is already a link to the English version in the upper right corner of the readme. Is it not conspicuous enough? Or do you think it needs to be improved?
