### ISSUE TITLE
编译错误：build/generated/android_aop/debug/null/DebugModeBuildConfig.java:1: 错误: 需要<标识符> package null;

### ISSUE THREAD

**Issue by wukongGit** [FlyJingFish/AndroidAOP#39]
### 描述一下大概怎么回事
编译错误

### 你的代码
![image](https://github.com/user-attachments/assets/769758c2-79bf-4ee9-a79c-ddcc3d965c4a)

### 错误日志
> Task :commonlib:compileDebugJavaWithJavac FAILED
/Users/user/work/commonlib/build/generated/android_aop/debug/null/DebugModeBuildConfig.java:1: 错误: 需要<标识符>
package null;
       ^
1 个错误

### 库的版本号:
2.2.3

### 电脑类别:
mac

**Comment by FlyJingFish** [comment]
已修复
