### ISSUE TITLE
自定切面ksp方式生效

### ISSUE THREAD

**Issue by Maplely** [FlyJingFish/AndroidAOP#40]
### 描述一下大概怎么回事
ksp方式不能生效 
annotationProcessor 可以

### 你的代码
![image](https://github.com/user-attachments/assets/d82227fc-3e91-4ed3-a986-405747524b45)
![image](https://github.com/user-attachments/assets/c427bc9f-47d5-4cc4-8423-0c68894822cf)

### 库的版本号:
 classpath('io.github.FlyJingFish.AndroidAop:android-aop-plugin:2.2.6')
 classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10'
 classpath('com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:1.8.10-1.0.9')
 implementation("io.github.FlyJingFish.AndroidAop:android-aop-core:2.2.6")
 ksp "io.github.FlyJingFish.AndroidAop:android-aop-ksp:2.2.6"
gradle:
![image](https://github.com/user-attachments/assets/53c2f1bf-1546-45c4-a9b2-8f85109a2248)

### 电脑类别:
mac

**Comment by FlyJingFish** [comment]
你用的不对

**Comment by Maplely** [comment]
具体哪里不对呢

**Comment by FlyJingFish** [comment]
你查一下ksp的用法，大家都一直在用着呢，而且你这写法也没啥特别的
