### ISSUE TITLE
和proguard冲突，导致proguard规则未生效

### ISSUE THREAD

**Issue by luomoxu** [FlyJingFish/AndroidAOP#45]
### 描述一下大概怎么回事
同时使用了ru.cleverpumpkin.proguard-dictionaries-generator
最后生成的apk文件中 proguard规则未生效,flattenpackagehierarchyc参数未生效

### 你的代码
根目录的`build.gradle`
```
plugins {
    id 'ru.cleverpumpkin.proguard-dictionaries-generator' version '1.0.8' apply false
    id 'com.android.application' version '8.7.3' apply false
    id 'com.android.library' version '8.7.3' apply false
    id 'org.jetbrains.kotlin.jvm' version "2.1.0" apply false
    id "io.github.FlyJingFish.AndroidAop.android-aop" version "2.3.3" apply true
    id 'com.google.devtools.ksp' version '2.1.0-1.0.29' apply false
}
```
项目目录的`build.gradle` 尝试过调整 proguard 的位置，但是都没效果
```
plugins {
    id 'com.android.application'
    id 'com.google.devtools.ksp'
    id 'android.aop'
    id 'ru.cleverpumpkin.proguard-dictionaries-generator'
}

dependencies {

    implementation 'io.github.FlyJingFish.AndroidAop:android-aop-core:2.3.3'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    ksp "io.github.FlyJingFish.AndroidAop:android-aop-ksp:2.3.3"

}
```
`proguard-rules.por` 开启了 flattenpackagehierarchy
```
flattenpackagehierarchy com.github.debug.merge
```

### 错误日志
构建未报错

### 库的版本号:
2.3.3

### 电脑类别:
windows 10
java 21
Gradle 2.9

**Comment by FlyJingFish** [comment]
没有混淆才是对的，混淆后会导致某些切面失效。目前的混淆规则是相对激进的。你可以试图去更改这些混淆规则，控制的更精细一点

**Comment by FlyJingFish** [comment]
保证需要切片的代码在混淆规则中是keep状态------是这个意思

你现在的配置看起来就是对的。我认为没有按你预期的走，应该还是代码之间有关联吧。切面代码主要是前两个切面需要注意，涉及到的方法及其方法上使用到的类都是不可以混淆的

**Comment by FlyJingFish** [comment]
嗯，有这个可能，你可以试着去改写引入插件的顺序。引入顺序决定了相应任务的顺序

**Comment by FlyJingFish** [comment]
那我先关闭了

**Comment by FlyJingFish** [comment]
对，我上边已经告诉过你了。现在的规则是比较激进的。你可以控制的更精细一点。
另外你现在写好了吗，可以发出来一块研究下

**Comment by FlyJingFish** [comment]
把### android-aop-core换成android-aop-annotation，然后把android-aop-core里的的代码全部copy下来，没多少东西

**Comment by FlyJingFish** [comment]
你按我说的先试试，看能否解决问题，明天我拿你的也试试，看各种情况下能不能正常跑起来。我这块需要考虑的比较多

**Comment by FlyJingFish** [comment]
Copy代码的时候，包名不能改，原封不动的复制

**Comment by FlyJingFish** [comment]
你确定能解决你的问题的话，明天我试试各种配置下，能不能正常跑起来。顺利的话明天我发包。前提是需要得到你的肯定的答复

**Comment by FlyJingFish** [comment]
> > 你确定能解决你的问题的话，明天我试试各种配置下，能不能正常跑起来。顺利的话明天我发包。前提是需要得到你的肯定的答复
> 
> 我的问题解决了 现在的规则应该会命中所有的类

是在最开始你提到的那个生产项目得到了验证是吧？

**Comment by FlyJingFish** [comment]
[最新版本](https://github.com/FlyJingFish/AndroidAOP/releases/tag/2.3.4)已更改混淆规则，代码也有所更改。你还是恢复到官方引入方式，去掉copy的那些本地代码
