### ISSUE TITLE
Toast Aop不成功

### ISSUE THREAD

**Issue by sher-loki** [FlyJingFish/AndroidAOP#5]
代码为
`@AndroidAopMatchClassMethod(
    targetClassName = "android.widget.Toast",
    methodName = ["show"],
    type = MatchType.EXTENDS
)
class ToastAop : MatchClassMethod {
    override fun invoke(joinPoint: ProceedJoinPoint, methodName: String): Any? {
        Log.e(
            "MatchTestMatchMethod",
            "======" + methodName + ",getParameterTypes=" + joinPoint.getTargetMethod()
                .getParameterTypes().size
        );
        return joinPoint.proceed()
    }
}
`
把这里换成
`@AndroidAopMatchClassMethod(
    targetClassName = "android.view.View.OnClickListener",
    methodName = ["onClick"],
    type = MatchType.EXTENDS 
)`
就可以了 所以我想是不是不支持Toast。
然后我看有个`AndroidAop.setOnToastListener`，试了一下，onToast方法也没有执行。

**Comment by FlyJingFish** [comment]
额……[你先看下这里](https://github.com/FlyJingFish/AndroidAOP?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)，其次```AndroidAop.setOnToastListener```,这是库里边有Toast。如果觉得库里用的Toast不是你想要的样式，可以设置这项换掉

**Comment by sher-loki** [comment]
喔喔理解了， 我还以为是比如我在代码里使用了toast.show，他就会把我代码里的toast给修改掉

**Comment by FlyJingFish** [comment]
> 喔喔理解了， 我还以为是比如我在代码里使用了toast.show，他就会把我代码里的toast给修改掉

最新版本1.3.6的[@AndroidAopReplaceClass](https://github.com/FlyJingFish/AndroidAOP/wiki/@AndroidAopReplaceClass)功能是你想的这种功能
