### ISSUE TITLE
AndroidAopMatchClassMethod 匹配类中所有的方法

### ISSUE THREAD

**Issue by hongyi0609** [FlyJingFish/AndroidAOP#8]
### 详细说明功能
我在使用AndroidAopMatchClassMethod时，发现其方法名methodName参数是必选项，这样就无法对匹配类的所有方法做处理，希望能解惑。比如我要统计，onCreate 方法中引用的init1、init2等方法的耗时，用起来很不方便

**Comment by FlyJingFish** [comment]
我考虑过是否应该给一个类所有方法都加切面，但是感觉这样的使用场景应该不多吧，或者说几乎不存在。因为我觉得不是所有方法都是需要被切面的，这么做可能会导致一些不可控的因素出现，例如开发者写的某些逻辑可能会导致有些方法不能被执行而不自知。因为我觉得应该让开发者显式的给匹配的类设置被切面的方法，尽管这样可能会麻烦一点，但开发者至少知道自己为哪些方法加了切面

**Comment by hongyi0609** [comment]
> 我考虑过是否应该给一个类所有方法都加切面，但是感觉这样的使用场景应该不多吧，或者说几乎不存在。因为我觉得不是所有方法都是需要被切面的，这么做可能会导致一些不可控的因素出现，例如开发者写的某些逻辑可能会导致有些方法不能被执行而不自知。所以我觉得应该让开发者显式的给匹配的类设置被切面的方法，尽管这样可能会麻烦一点，但开发者至少知道自己为哪些方法加了切面。 如果你还是觉得这种功能有必要的话，请把你的实际使用场景详细介绍出来，我再来评估是否应该加上这样的功能

有两个场景可以参考，一个是做性能优化的时候，牵涉到初始化多个三方插件，这里需要做时间统计。另一个引用三方库的时候，如果想要统计第三方插件的耗时，也必须要知道其方法名。

**Comment by FlyJingFish** [comment]
> > 我考虑过是否应该给一个类所有方法都加切面，但是感觉这样的使用场景应该不多吧，或者说几乎不存在。因为我觉得不是所有方法都是需要被切面的，这么做可能会导致一些不可控的因素出现，例如开发者写的某些逻辑可能会导致有些方法不能被执行而不自知。所以我觉得应该让开发者显式的给匹配的类设置被切面的方法，尽管这样可能会麻烦一点，但开发者至少知道自己为哪些方法加了切面。 如果你还是觉得这种功能有必要的话，请把你的实际使用场景详细介绍出来，我再来评估是否应该加上这样的功能
> 
> 有两个场景可以参考，一个是做性能优化的时候，牵涉到初始化多个三方插件，这里需要做时间统计。另一个引用三方库的时候，如果想要统计第三方插件的耗时，也必须要知道其方法名。

你需要清楚的是，AndroidAopMatchClassMethod 只会给其设置的类的方法加入切面代码，而不包括设置的类里边调用的其他类的方法加入切面，而且市面上也没有这种功能的库的

**Comment by hongyi0609** [comment]
> > > 我考虑过是否应该给一个类所有方法都加切面，但是感觉这样的使用场景应该不多吧，或者说几乎不存在。因为我觉得不是所有方法都是需要被切面的，这么做可能会导致一些不可控的因素出现，例如开发者写的某些逻辑可能会导致有些方法不能被执行而不自知。所以我觉得应该让开发者显式的给匹配的类设置被切面的方法，尽管这样可能会麻烦一点，但开发者至少知道自己为哪些方法加了切面。 如果你还是觉得这种功能有必要的话，请把你的实际使用场景详细介绍出来，我再来评估是否应该加上这样的功能
> > 
> > 
> > 有两个场景可以参考，一个是做性能优化的时候，牵涉到初始化多个三方插件，这里需要做时间统计。另一个引用三方库的时候，如果想要统计第三方插件的耗时，也必须要知道其方法名。
> 
> 你需要清楚的是，AndroidAopMatchClassMethod 只会给其设置的类的方法加入切面代码，而不包括设置的类里边调用的其他类的方法加入切面，而且市面上也没有这种功能的库的

老师，你理解错我的意思了。我更关注统计当前类的所有方法～

**Comment by FlyJingFish** [comment]
> > > > 我考虑过是否应该给一个类所有方法都加切面，但是感觉这样的使用场景应该不多吧，或者说几乎不存在。因为我觉得不是所有方法都是需要被切面的，这么做可能会导致一些不可控的因素出现，例如开发者写的某些逻辑可能会导致有些方法不能被执行而不自知。所以我觉得应该让开发者显式的给匹配的类设置被切面的方法，尽管这样可能会麻烦一点，但开发者至少知道自己为哪些方法加了切面。 如果你还是觉得这种功能有必要的话，请把你的实际使用场景详细介绍出来，我再来评估是否应该加上这样的功能
> > > 
> > > 
> > > 有两个场景可以参考，一个是做性能优化的时候，牵涉到初始化多个三方插件，这里需要做时间统计。另一个引用三方库的时候，如果想要统计第三方插件的耗时，也必须要知道其方法名。
> > 
> > 
> > 你需要清楚的是，AndroidAopMatchClassMethod 只会给其设置的类的方法加入切面代码，而不包括设置的类里边调用的其他类的方法加入切面，而且市面上也没有这种功能的库的
> 
> 老师，你理解错我的意思了。我更关注统计当前类的所有方法～

哦～我明白你的意思了，你是想看一下所有方法执行的时间然后看哪个时间长来针对性的做优化。但这种场景做完代码是不是就删除了呢？所以这是一种临时性的场景？因此我认为前面我介绍的情况更重要
对于此种情况我认为你可以利用反射获取到一个类的所有方法，然后拼接成字符串数组并打印出来，然后填写到 AndroidAopMatchClassMethod 即可。时间并不会浪费多久的～

**Comment by FlyJingFish** [comment]
> 我也有类似的需求，作者是否可以考虑加上类似于AspectJ的模糊匹配的机制呢？

你也是匹配类中的所有方法？

**Comment by CodeReverse** [comment]
> > 我也有类似的需求，作者是否可以考虑加上类似于AspectJ的模糊匹配的机制呢？
> 
> 你也是匹配类中的所有方法？

是的，跟这个issue里提到的问题类似，统计方法执行耗时，统计无用代码这样类似的需求

**Comment by FlyJingFish** [comment]
既然你提到了AspectJ 我也说下当初为什么这么设计。考虑AspectJ的匹配规则过于宽泛，导致一些新手在用的时候常常是插入的切面代码多于开发者所想的，因此我才设计了这个规则（必须要至少填一个不写返回类型和参数类型的方法名），即显式的设置方法名，如此一来所有的使用者对自己的代码是有着“掌控”的
不过提到这个需求的人多起来了，我肯定要考虑一下的。毕竟也要考虑一下一部分“高级玩家”的需求。我平衡一下吧，看看如何在不抛弃前边所考虑的前提下，加上更为模糊的匹配规则

**Comment by CodeReverse** [comment]
> 既然你提到了AspectJ 我也说下当初为什么这么设计。考虑AspectJ的匹配规则过于宽泛，导致一些新手在用的时候常常是插入的切面代码多于开发者所想的，因此我才设计了这个规则（必须要至少填一个不写返回类型和参数类型的方法名），即显式的设置方法名，如此一来所有的使用者对自己的代码是有着“掌控”的 不过提到这个需求的人多起来了，我肯定要考虑一下的。毕竟也要考虑一下一部分“高级玩家”的需求。我平衡一下吧，看看如何在不抛弃前边所考虑的前提下，加上更为模糊的匹配规则

我明白你的顾虑，更精准的配置有助于控制织入代码的颗粒度，目前框架提供的方法也能够实现我们的需求，更加模糊的匹配规则可以在实现上更加方便一些。
最后感谢大佬的及时回复以及提供这么好的框架~

**Comment by hongyi0609** [comment]
> > > > > 我考虑过是否应该给一个类所有方法都加切面，但是感觉这样的使用场景应该不多吧，或者说几乎不存在。因为我觉得不是所有方法都是需要被切面的，这么做可能会导致一些不可控的因素出现，例如开发者写的某些逻辑可能会导致有些方法不能被执行而不自知。所以我觉得应该让开发者显式的给匹配的类设置被切面的方法，尽管这样可能会麻烦一点，但开发者至少知道自己为哪些方法加了切面。 如果你还是觉得这种功能有必要的话，请把你的实际使用场景详细介绍出来，我再来评估是否应该加上这样的功能
> > > > 
> > > > 
> > > > 有两个场景可以参考，一个是做性能优化的时候，牵涉到初始化多个三方插件，这里需要做时间统计。另一个引用三方库的时候，如果想要统计第三方插件的耗时，也必须要知道其方法名。
> > > 
> > > 
> > > 你需要清楚的是，AndroidAopMatchClassMethod 只会给其设置的类的方法加入切面代码，而不包括设置的类里边调用的其他类的方法加入切面，而且市面上也没有这种功能的库的
> > 
> > 
> > 老师，你理解错我的意思了。我更关注统计当前类的所有方法～
> 
> 哦～我明白你的意思了，你是想看一下所有方法执行的时间然后看哪个时间长来针对性的做优化。但这种场景做完代码是不是就删除了呢？所以这是一种临时性的场景？因此我认为前面我介绍的情况更重要 对于此种情况我认为你可以利用反射获取到一个类的所有方法，然后拼接成字符串数组并打印出来，然后填写到 AndroidAopMatchClassMethod 即可。时间并不会浪费多久的～

感谢大佬～

**Comment by FlyJingFish** [comment]
[最新版本已经支持匹配所有方法](https://github.com/FlyJingFish/AndroidAOP/releases/tag/1.4.4)

**Comment by hongyi0609** [comment]
> [最新版本已经支持匹配所有方法](https://github.com/FlyJingFish/AndroidAOP/releases/tag/1.4.4)

貌似有 bug，切面中的逻辑影响 CountDownLatch 执行 countdown，直接ANR 了。

**Comment by hongyi0609** [comment]
<img width="735" alt="image" src="https://github.com/FlyJingFish/AndroidAOP/assets/17640654/0866eaf1-6665-44d6-a5ce-d549bf69facf">

**Comment by FlyJingFish** [comment]
> > [最新版本已经支持匹配所有方法](https://github.com/FlyJingFish/AndroidAOP/releases/tag/1.4.4)
> 
> 貌似有 bug，切面中的逻辑影响 CountDownLatch 执行 countdown，直接ANR 了。

你自己的问题，这个类你在主线程用调用的吧

**Comment by hongyi0609** [comment]
> > > [最新版本已经支持匹配所有方法](https://github.com/FlyJingFish/AndroidAOP/releases/tag/1.4.4)
> > 
> > 
> > 貌似有 bug，切面中的逻辑影响 CountDownLatch 执行 countdown，直接ANR 了。
> 
> 你自己的问题，这个类你在主线程用调用的吧

确实切在application 里了

**Comment by hongyi0609** [comment]
> > > [最新版本已经支持匹配所有方法](https://github.com/FlyJingFish/AndroidAOP/releases/tag/1.4.4)
> > 
> > 
> > 貌似有 bug，切面中的逻辑影响 CountDownLatch 执行 countdown，直接ANR 了。
> 
> 你自己的问题，这个类你在主线程用调用的吧

我的锅，学习了～
<img width="873" alt="image" src="https://github.com/FlyJingFish/AndroidAOP/assets/17640654/2dcf5c40-22a9-4c1e-9055-370100e7ed3a">
