### ISSUE TITLE
classes.jar文件删除问题

### ISSUE THREAD

**Issue by fuchengxin** [FlyJingFish/AndroidAOP#9]
目前集成的版本是1.4.7，在使用aop库之后，每次编译都会出现classes.jar文件删不掉的错误提示，需要手动去任务管理器的资源监视器删除，但是每次编译都会出现这样的问题，请问这个与集成aop是否有关系，aop是否会导致在编译时classes.jar可能删不掉的问题？
![image](https://github.com/FlyJingFish/AndroidAOP/assets/15795966/53226fa7-2851-44cb-8782-9e6495592a57)

![image](https://github.com/FlyJingFish/AndroidAOP/assets/15795966/70ea8a5b-4f21-42ae-ae7c-7697d2920e90)

**Comment by FlyJingFish** [comment]
1、你使用了库里的哪些功能呢
2、另外你只要一去掉这个库就没事了吗

**Comment by fuchengxin** [comment]
ksp "io.github.FlyJingFish.AndroidAop:android-aop-ksp:$aop_version"  我去除每个module下面的这一句就好了

**Comment by FlyJingFish** [comment]
这句应该不会导致这种问题的，你的问题是否得到了解决呢？如果解决我就关闭这个问题了

**Comment by fuchengxin** [comment]
我需要用到这个库的自定义注解，非静态方法的时候我可以通过target拿到activity，但是静态方法target是null，请问怎么拿到activity
![image](https://github.com/FlyJingFish/AndroidAOP/assets/15795966/da2b69db-c612-4c32-a305-c4b9853cba74)

**Comment by hiquanta** [comment]
我也是集成之后遇到classes.jar删除不掉，不过关闭，或者管理员权限打开，就可以了，不知道是不是这个原因

**Comment by fuchengxin** [comment]
> 我也是集成之后遇到classes.jar删除不掉，不过关闭，或者管理员权限打开，就可以了，不知道是不是这个原因

这个不是编译器自己生成的吗，怎么用管理员权限打开，请问你操作之后就没有这个问题了还是 编译经常仍然能碰到

**Comment by FlyJingFish** [comment]
> 我需要用到这个库的自定义注解，非静态方法的时候我可以通过target拿到activity，但是静态方法target是null，请问怎么拿到activity ![image](https://private-user-images.githubusercontent.com/15795966/313059526-da2b69db-c612-4c32-a305-c4b9853cba74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NzQxNjksIm5iZiI6MTcxMDQ3Mzg2OSwicGF0aCI6Ii8xNTc5NTk2Ni8zMTMwNTk1MjYtZGEyYjY5ZGItYzYxMi00YzMyLWEzMDUtYzRiOTg1M2NiYTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAzMzc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlN2IzYmM3NDQzNTM0ODlkZmRmNmE0YTQxNWYzZDliY2I2M2ZhNGVkNGFkZmViYjVkM2MyOTY2MWJmYWQ4OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3HvzCGCjFolklnLqsG0F2Vi3Vzb96pa7onE3e75_6pk)

所谓的 ```target``` 是方法所在的对象，静态方法不属于对象，所以 ```target``` 是null 。另外想要拿到某些对象的话可以参考这里[切面启示](https://github.com/FlyJingFish/AndroidAOP/wiki/%E5%88%87%E9%9D%A2%E5%90%AF%E7%A4%BA#2%E5%8F%A6%E5%A4%96%E5%AF%B9%E4%BA%8E%E5%88%87%E9%9D%A2%E6%B3%A8%E8%A7%A3%E6%98%AF%E6%B2%A1%E5%8A%9E%E6%B3%95%E4%BC%A0%E5%85%A5%E5%AF%B9%E8%B1%A1%E4%BB%80%E4%B9%88%E7%9A%84%E6%88%96%E8%80%85%E6%95%B0%E6%8D%AE%E6%98%AF%E5%8A%A8%E6%80%81%E7%9A%84%E9%82%A3%E6%80%8E%E4%B9%88%E5%8A%9E%E5%91%A2)

**Comment by FlyJingFish** [comment]
[点此查看解决方法！](https://flyjingfish.github.io/AndroidAOP/zh/FAQ/#7windows)
